unstable_features = true
edition = "2021"

wrap_comments = true
format_code_in_doc_comments = true
format_strings = true
match_block_trailing_comma = true
normalize_comments = true
use_field_init_shorthand = true
