[package]
name = "skrillax-security"
version = "0.1.0"
edition = "2021"

[dependencies]
blowfish-compat = { git = "https://git.eternalwings.de/tim/blowfish-compat.rs.git", branch = "master" }
bytes.workspace = true
byteorder.workspace = true
rand = "0.8"
thiserror.workspace = true
once_cell = "1"