[package]
name = "skrillax-security"
version = "0.1.0"
edition = "2021"

[dependencies]
blowfish = { version = "0.9.1" }
bytes.workspace = true
byteorder.workspace = true
rand = "0.8"
thiserror.workspace = true
once_cell = "1"
bitflags = "2.5"