[package]
name = "skrillax-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes.workspace = true
byteorder.workspace = true
skrillax-serde-derive = { path = "../skrillax-serde-derive", optional = true }
chrono = "0.4"
paste = "1"
thiserror.workspace = true

[features]
derive = ["dep:skrillax-serde-derive"]