[package]
name = "skrillax-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6"
skrillax-serde-derive = { path = "../skrillax-serde-derive", optional = true }
chrono = "0.4"
paste = "1"
byteorder = "1.5"
thiserror = "1.0"

[features]
derive = ["dep:skrillax-serde-derive"]