#![cfg(test)]

use bytes::BytesMut;
use skrillax_serde::{
    ByteSize, DeserializationLimits, Deserialize, SerdeContext, SerializationError, Serialize,
};
use std::fmt::Debug;
use std::io::Cursor;

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct Test {
    one: u8,
    two: u16,
    three: u32,
    four: u64,
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
enum TestEnum {
    #[silkroad(value = 1)]
    A,
    #[silkroad(value = 2)]
    B(u8),
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct Wrapped {
    inner: Test,
    inner2: TestEnum,
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct NormalString(String);

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct DoubleString(#[silkroad(size = 2)] String);

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct WithVec(Vec<u32>);

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
enum EnumWithNamedVec {
    #[silkroad(value = 1)]
    Variant { inner: Vec<Test> },
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct StringCollection(Vec<String>);

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct TestCond {
    cond: u8,
    unrelated: String,
    #[silkroad(when = "cond == 1")]
    value: Option<u8>,
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
#[silkroad(size = 2)]
enum LargerEnum {
    #[silkroad(value = 1)]
    A,
    #[silkroad(value = 0xFFF)]
    B,
}

/// Assert the complete contract for a successfully serialized value.
///
/// The prefix proves that serialization writes at the current buffer position,
/// while the trailing canary proves that deserialization stops exactly at the
/// end of the value.
fn assert_round_trip<T>(value: T, expected: &[u8], ctx: &SerdeContext)
where
    T: Serialize + Deserialize + Eq + Debug,
    bytes::Bytes: TryFrom<T, Error = SerializationError>,
{
    assert_eq!(expected.len(), value.byte_size());

    const PREFIX: &[u8] = &[0xA5, 0x5A];
    let mut output = BytesMut::from(PREFIX);
    let initial_len = output.len();

    let result = value.write_to(&mut output, ctx);
    assert!(result.is_ok(), "serialization failed: {:?}", result);
    assert_eq!(PREFIX, &output[..initial_len]);

    let written = &output[initial_len..];
    assert_eq!(value.byte_size(), written.len());
    assert_eq!(expected, written);

    let decoded = assert_deserializes_exactly::<T>(expected, ctx);
    assert_eq!(value, decoded);

    let converted = bytes::Bytes::try_from(value).expect("generated byte conversion failed");
    assert_eq!(expected, converted.as_ref());
}

fn assert_context_round_trip<T>(value: T, expected: &[u8], ctx: &SerdeContext)
where
    T: Serialize + Deserialize + ByteSize + Eq + Debug,
{
    assert_eq!(expected.len(), value.byte_size());
    let mut output = BytesMut::new();
    value
        .write_to(&mut output, ctx)
        .expect("serialization with context failed");
    assert_eq!(expected, output.as_ref());
    assert_eq!(value, assert_deserializes_exactly(expected, ctx));
}

/// Deserialize a value with a trailing canary and verify that the reader
/// consumed exactly the value, not any following bytes.
fn assert_deserializes_exactly<T>(expected: &[u8], ctx: &SerdeContext) -> T
where
    T: Deserialize,
{
    const CANARY: &[u8] = &[0xCA, 0xFE, 0xBA, 0xBE];
    let mut input = Vec::with_capacity(expected.len() + CANARY.len());
    input.extend_from_slice(expected);
    input.extend_from_slice(CANARY);
    let mut reader = Cursor::new(input);
    let decoded = T::read_from(&mut reader, ctx).expect("deserialization failed");

    assert_eq!(expected.len() as u64, reader.position());
    assert_eq!(CANARY, &reader.get_ref()[reader.position() as usize..]);
    decoded
}

fn context_with_collection_limit(maximum: usize) -> SerdeContext {
    let context = SerdeContext::default();
    context
        .set_deserialization_limits(DeserializationLimits::with_max_collection_elements(maximum));
    context
}

/// Assert that serialization returns the expected typed error.
#[allow(dead_code)]
fn assert_serialization_error<T, F>(value: &T, ctx: &SerdeContext, matches: F)
where
    T: Serialize,
    F: FnOnce(&SerializationError) -> bool,
{
    let mut output = BytesMut::new();
    let error = value
        .write_to(&mut output, ctx)
        .expect_err("serialization unexpectedly succeeded");
    assert!(matches(&error), "unexpected serialization error: {error:?}");
}

macro_rules! test_serialize_deserialize {
    ($ty:ty, $init:expr, $expected:expr) => {{
        assert_round_trip::<$ty>($init, $expected, &SerdeContext::default());
    }};
}

#[test]
pub fn test_simple() {
    test_serialize_deserialize!(
        Test,
        Test {
            one: 1,
            two: 2,
            three: 3,
            four: 4,
        },
        &[1, 2, 0, 3, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0]
    );
}

#[test]
pub fn test_enum() {
    test_serialize_deserialize!(TestEnum, TestEnum::A, &[1]);
    test_serialize_deserialize!(TestEnum, TestEnum::B(1), &[2, 1]);
}

#[test]
pub fn test_wrapped() {
    test_serialize_deserialize!(
        Wrapped,
        Wrapped {
            inner: Test {
                one: 1,
                two: 2,
                three: 3,
                four: 4,
            },
            inner2: TestEnum::B(3),
        },
        &[1, 2, 0, 3, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 2, 3,]
    );
}

#[test]
pub fn test_strings() {
    test_serialize_deserialize!(
        NormalString,
        NormalString("123".to_string()),
        &[3, 0, b'1', b'2', b'3']
    );
    test_serialize_deserialize!(
        DoubleString,
        DoubleString("456".to_string()),
        &[3, 0, b'4', 0, b'5', 0, b'6', 0]
    );
}

#[test]
pub fn test_vec() {
    test_serialize_deserialize!(
        WithVec,
        WithVec(vec![123, 456, 789]),
        &[3, 123, 0, 0, 0, 200, 1, 0, 0, 21, 3, 0, 0]
    );
    test_serialize_deserialize!(
        EnumWithNamedVec,
        EnumWithNamedVec::Variant {
            inner: vec![Test {
                one: 0,
                two: 0,
                three: 0,
                four: 0,
            }],
        },
        &[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]
    );
}

#[test]
pub fn test_string_collection() {
    assert_round_trip(
        StringCollection(vec!["é".into(), "ok".into()]),
        &[2, 2, 0, 0xc3, 0xa9, 2, 0, b'o', b'k'],
        &SerdeContext::default(),
    );
}

#[test]
pub fn test_cond() {
    test_serialize_deserialize!(
        TestCond,
        TestCond {
            cond: 1,
            unrelated: String::from("abc"),
            value: Some(1),
        },
        &[1, 3, 0, b'a', b'b', b'c', 1]
    );

    test_serialize_deserialize!(
        TestCond,
        TestCond {
            cond: 0,
            unrelated: String::from("abc"),
            value: None,
        },
        &[0, 3, 0, b'a', b'b', b'c']
    );
}

#[test]
pub fn test_large_enum() {
    test_serialize_deserialize!(LargerEnum, LargerEnum::B, &[0xFF, 0x0F]);
}

#[test]
pub fn test_unknown_variant() {
    let bytes = bytes::Bytes::from_static(&[3u8]);
    assert!(matches!(
        TestEnum::try_from(bytes),
        Err(skrillax_serde::SerializationError::UnknownVariation(
            3, "TestEnum"
        ))
    ));
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
#[silkroad(size = 2)]
enum TaggedEnum {
    #[silkroad(when = "tag < 100")]
    A {
        #[silkroad(tag)]
        value: u16,
    },
    #[silkroad(when = "(100..=300).contains(&tag)")]
    B {
        #[silkroad(tag)]
        value: u16,
    },
    #[silkroad(when = "tag >= 301")]
    C {
        #[silkroad(tag)]
        value: u16,
    },
}

#[test]
pub fn test_tagged_enum() {
    test_serialize_deserialize!(TaggedEnum, TaggedEnum::A { value: 50 }, &[50, 0]);
    test_serialize_deserialize!(TaggedEnum, TaggedEnum::B { value: 150 }, &[150, 0]);
    test_serialize_deserialize!(TaggedEnum, TaggedEnum::C { value: 1240 }, &[0xD8, 0x04]);
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
enum GappedPredicateEnum {
    #[silkroad(when = "tag == 1")]
    One {
        #[silkroad(tag)]
        tag: u8,
    },
    #[silkroad(when = "tag == 2")]
    Two {
        #[silkroad(tag)]
        tag: u8,
    },
}

#[test]
fn predicate_enum_without_a_matching_tag_returns_a_typed_error() {
    let error = GappedPredicateEnum::read_from(&mut Cursor::new([3]), &SerdeContext::default())
        .expect_err("unmatched predicate tag must fail");
    assert!(matches!(
        error,
        SerializationError::NoMatchingVariant {
            enum_name: "GappedPredicateEnum"
        }
    ));
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
#[silkroad(size = 2)]
enum TaggedTupleEnum {
    #[silkroad(when = "tag < 100")]
    A(#[silkroad(tag)] u16),
    #[silkroad(when = "(100..=300).contains(&tag)")]
    B(#[silkroad(tag)] u16),
    #[silkroad(when = "tag >= 301")]
    C(#[silkroad(tag)] u16),
}

#[test]
pub fn test_tagged_tuple_enum() {
    test_serialize_deserialize!(TaggedTupleEnum, TaggedTupleEnum::A(50), &[50, 0]);
    test_serialize_deserialize!(TaggedTupleEnum, TaggedTupleEnum::B(150), &[150, 0]);
    test_serialize_deserialize!(TaggedTupleEnum, TaggedTupleEnum::C(1240), &[0xD8, 0x04]);
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct UnicodeStrings {
    utf8: String,
    #[silkroad(size = 2)]
    utf16: String,
    trailing: u8,
}

#[test]
fn unicode_string_lengths_use_their_wire_units() {
    assert_round_trip(
        UnicodeStrings {
            utf8: "é😀".into(),
            utf16: "é😀".into(),
            trailing: 0x7f,
        },
        &[
            0x06, 0x00, 0xc3, 0xa9, 0xf0, 0x9f, 0x98, 0x80, // UTF-8 bytes
            0x03, 0x00, 0xe9, 0x00, 0x3d, 0xd8, 0x00, 0xde, // UTF-16 units
            0x7f,
        ],
        &SerdeContext::default(),
    );
}

#[derive(Serialize, ByteSize)]
struct OversizedString {
    prefix: u8,
    value: String,
}

#[test]
fn oversized_string_fails_before_its_prefix_and_preserves_prior_output() {
    let value = OversizedString {
        prefix: 0x44,
        value: "x".repeat(usize::from(u16::MAX) + 1),
    };
    let mut output = BytesMut::from(&b"keep"[..]);
    let original = output.len();
    let error = value
        .write_to(&mut output, &SerdeContext::default())
        .expect_err("oversized string must fail");
    assert!(matches!(
        error,
        SerializationError::LengthOutOfRange {
            field: "value",
            actual: 65_536,
            maximum: 65_535,
            width: 2,
        }
    ));
    assert_eq!(&output[..original], b"keep");
    assert_eq!(&output[original..], &[0x44]);
    output.truncate(original);
    assert_eq!(output.as_ref(), b"keep");
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct CountedWidths {
    #[silkroad(size = 1)]
    one: Vec<u8>,
    #[silkroad(size = 2)]
    two: Vec<u8>,
    #[silkroad(size = 4)]
    four: Vec<u8>,
    #[silkroad(size = 8)]
    eight: Vec<u8>,
}

#[test]
fn counted_collections_honor_all_integer_widths() {
    assert_round_trip(
        CountedWidths {
            one: vec![1],
            two: vec![2],
            four: vec![3],
            eight: vec![4],
        },
        &[
            1, 1, // u8 count
            1, 0, 2, // u16 count
            1, 0, 0, 0, 3, // u32 count
            1, 0, 0, 0, 0, 0, 0, 0, 4, // u64 count
        ],
        &context_with_collection_limit(1),
    );
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct CountedFour {
    #[silkroad(size = 4)]
    items: Vec<u8>,
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct CountedEight {
    #[silkroad(size = 8)]
    items: Vec<u8>,
}

#[test]
fn counted_collections_accept_counts_equal_to_the_limit() {
    let context = context_with_collection_limit(2);

    assert_eq!(
        CountedFour::read_from(&mut Cursor::new([2, 0, 0, 0, 7, 8]), &context).unwrap(),
        CountedFour { items: vec![7, 8] }
    );
    assert_eq!(
        CountedEight::read_from(&mut Cursor::new([2, 0, 0, 0, 0, 0, 0, 0, 7, 8]), &context,)
            .unwrap(),
        CountedEight { items: vec![7, 8] }
    );
}

#[test]
fn counted_collection_limit_errors_are_lossless_and_leave_payload_unread() {
    let context = context_with_collection_limit(2);
    let mut four_byte_reader = Cursor::new([3, 0, 0, 0, 0xaa]);
    let error = CountedFour::read_from(&mut four_byte_reader, &context)
        .expect_err("u32 count above the policy must fail");
    assert!(matches!(
        error,
        SerializationError::CollectionLengthLimitExceeded {
            field: "items",
            actual: 3,
            maximum: 2,
        }
    ));
    assert_eq!(four_byte_reader.position(), 4);
    assert_eq!(&four_byte_reader.get_ref()[4..], &[0xaa]);

    let mut eight_byte_input = u64::MAX.to_le_bytes().to_vec();
    eight_byte_input.push(0xbb);
    let mut eight_byte_reader = Cursor::new(eight_byte_input);
    let error = CountedEight::read_from(&mut eight_byte_reader, &context)
        .expect_err("u64::MAX must be checked before conversion or allocation");
    assert!(matches!(
        error,
        SerializationError::CollectionLengthLimitExceeded {
            field: "items",
            actual: u64::MAX,
            maximum: 2,
        }
    ));
    assert_eq!(eight_byte_reader.position(), 8);
    assert_eq!(&eight_byte_reader.get_ref()[8..], &[0xbb]);
}

#[test]
fn counted_prefix_errors_precede_collection_policy_checks() {
    let context = context_with_collection_limit(0);
    let error = CountedFour::read_from(&mut Cursor::new([1, 0]), &context)
        .expect_err("a truncated count prefix must fail before the limit is checked");

    assert!(matches!(
        error,
        SerializationError::FieldIoError("items", source)
            if source.kind() == std::io::ErrorKind::UnexpectedEof
    ));
}

#[test]
fn configured_counted_limit_accepts_counts_below_the_maximum() {
    let context = context_with_collection_limit(2);
    let decoded = CountedWidths::read_from(
        &mut Cursor::new([
            1, 1, // u8 count
            1, 0, 2, // u16 count
            1, 0, 0, 0, 3, // u32 count
            1, 0, 0, 0, 0, 0, 0, 0, 4, // u64 count
        ]),
        &context,
    )
    .unwrap();

    assert_eq!(decoded.one, vec![1]);
    assert_eq!(decoded.two, vec![2]);
    assert_eq!(decoded.four, vec![3]);
    assert_eq!(decoded.eight, vec![4]);
}

#[test]
fn a_zero_limit_accepts_zero_counted_elements() {
    let context = context_with_collection_limit(0);

    assert_eq!(
        CountedFour::read_from(&mut Cursor::new([0, 0, 0, 0, 0xaa]), &context).unwrap(),
        CountedFour { items: Vec::new() }
    );
}

#[test]
fn receive_limits_do_not_affect_serialization_or_byte_size() {
    let value = CountedFour { items: vec![7, 8] };
    let context = context_with_collection_limit(1);
    let expected = [2, 0, 0, 0, 7, 8];
    let mut output = BytesMut::new();

    assert_eq!(value.byte_size(), expected.len());
    value.write_to(&mut output, &context).unwrap();
    assert_eq!(output.as_ref(), expected);

    let error = CountedFour::read_from(&mut Cursor::new(&expected), &context)
        .expect_err("restricted decoding must reject the serialized collection");
    assert!(matches!(
        error,
        SerializationError::CollectionLengthLimitExceeded {
            field: "items",
            actual: 2,
            maximum: 1,
        }
    ));
    assert_eq!(
        CountedFour::read_from(&mut Cursor::new(&expected), &SerdeContext::default()).unwrap(),
        value
    );
}

#[cfg(target_pointer_width = "64")]
#[test]
fn counted_capacity_overflow_returns_a_typed_allocation_error() {
    let mut reader = Cursor::new(u64::MAX.to_le_bytes());
    let error = CountedEight::read_from(&mut reader, &SerdeContext::default())
        .expect_err("usize::MAX elements cannot be reserved for Vec<u8>");

    assert!(matches!(
        error,
        SerializationError::CollectionAllocationFailed {
            field: "items",
            elements: u64::MAX,
            ..
        }
    ));
    assert_eq!(reader.position(), 8);
}

#[cfg(target_pointer_width = "32")]
#[test]
fn counted_capacity_overflow_and_numeric_range_errors_remain_distinct() {
    let error = CountedFour::read_from(
        &mut Cursor::new(u32::MAX.to_le_bytes()),
        &SerdeContext::default(),
    )
    .expect_err("usize::MAX elements cannot be reserved for Vec<u8>");
    assert!(matches!(
        error,
        SerializationError::CollectionAllocationFailed {
            field: "items",
            elements: value,
            ..
        } if value == u64::from(u32::MAX)
    ));

    let error = CountedEight::read_from(
        &mut Cursor::new(u64::MAX.to_le_bytes()),
        &SerdeContext::default(),
    )
    .expect_err("u64::MAX cannot be represented as usize");
    assert!(matches!(
        error,
        SerializationError::DecodedLengthOutOfRange {
            field: "items",
            value: u64::MAX,
        }
    ));
}

#[derive(Serialize, ByteSize)]
struct CountOverflow {
    prefix: u8,
    #[silkroad(size = 1)]
    values: Vec<u8>,
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct CountedU8(Vec<u8>);

#[test]
fn one_byte_count_accepts_its_maximum_value() {
    let value = CountedU8(vec![0x5a; 255]);
    let mut expected = vec![255];
    expected.extend_from_slice(&value.0);
    assert_round_trip(value, &expected, &SerdeContext::default());
}

#[test]
fn counted_collection_overflow_is_typed_and_does_not_write_a_prefix() {
    let value = CountOverflow {
        prefix: 9,
        values: vec![0; 256],
    };
    let mut output = BytesMut::new();
    let error = value
        .write_to(&mut output, &SerdeContext::default())
        .expect_err("u8 count must overflow");
    assert!(matches!(
        error,
        SerializationError::LengthOutOfRange {
            field: "values",
            actual: 256,
            maximum: 255,
            width: 1,
        }
    ));
    assert_eq!(output.as_ref(), &[9]);

    let error = bytes::Bytes::try_from(CountOverflow {
        prefix: 9,
        values: vec![0; 256],
    })
    .expect_err("generated TryFrom must preserve the serialization error");
    assert!(matches!(
        error,
        SerializationError::LengthOutOfRange {
            field: "values",
            actual: 256,
            maximum: 255,
            width: 1,
        }
    ));
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct BreakSequence(#[silkroad(list_type = "break", size = 2)] Vec<u8>);

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct HasMoreSequence(#[silkroad(list_type = "has-more", size = 4)] Vec<u8>);

#[test]
fn sentinel_collections_honor_widths_and_terminal_markers() {
    assert_round_trip(
        BreakSequence(vec![7, 8]),
        &[1, 0, 7, 1, 0, 8, 2, 0],
        &SerdeContext::default(),
    );
    assert_round_trip(
        HasMoreSequence(Vec::new()),
        &[0, 0, 0, 0],
        &SerdeContext::default(),
    );
}

macro_rules! sentinel_type {
    ($name:ident, $framing:literal, $width:literal) => {
        #[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
        struct $name(#[silkroad(list_type = $framing, size = $width)] Vec<u8>);
    };
}

sentinel_type!(Break1, "break", 1);
sentinel_type!(Break4, "break", 4);
sentinel_type!(Break8, "break", 8);
sentinel_type!(HasMore1, "has-more", 1);
sentinel_type!(HasMore2, "has-more", 2);
sentinel_type!(HasMore8, "has-more", 8);

#[test]
fn both_sentinel_styles_support_every_marker_width() {
    assert_round_trip(Break1(vec![9]), &[1, 9, 2], &SerdeContext::default());
    assert_round_trip(
        Break4(vec![9]),
        &[1, 0, 0, 0, 9, 2, 0, 0, 0],
        &SerdeContext::default(),
    );
    assert_round_trip(
        Break8(vec![9]),
        &[1, 0, 0, 0, 0, 0, 0, 0, 9, 2, 0, 0, 0, 0, 0, 0, 0],
        &SerdeContext::default(),
    );
    assert_round_trip(HasMore1(vec![9]), &[1, 9, 0], &SerdeContext::default());
    assert_round_trip(
        HasMore2(vec![9]),
        &[1, 0, 9, 0, 0],
        &SerdeContext::default(),
    );
    assert_round_trip(
        HasMore8(vec![9]),
        &[1, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0],
        &SerdeContext::default(),
    );
}

#[test]
fn invalid_collection_markers_are_rejected() {
    let error = BreakSequence::read_from(&mut Cursor::new([3, 0]), &SerdeContext::default())
        .expect_err("invalid break marker must fail");
    assert!(matches!(
        error,
        SerializationError::InvalidSequenceMarker {
            field: "t0",
            value: 3
        }
    ));

    let error =
        HasMoreSequence::read_from(&mut Cursor::new([2, 0, 0, 0]), &SerdeContext::default())
            .expect_err("invalid has-more marker must fail");
    assert!(matches!(
        error,
        SerializationError::InvalidSequenceMarker {
            field: "t0",
            value: 2
        }
    ));
}

#[test]
fn sentinel_collections_enforce_limits_before_excess_item_payloads() {
    let context = context_with_collection_limit(1);

    assert_eq!(
        Break1::read_from(&mut Cursor::new([1, 7, 2]), &context).unwrap(),
        Break1(vec![7])
    );
    let mut break_reader = Cursor::new([1, 7, 1, 0xaa, 2]);
    let error = Break1::read_from(&mut break_reader, &context)
        .expect_err("second break-framed element must exceed the policy");
    assert!(matches!(
        error,
        SerializationError::CollectionLengthLimitExceeded {
            field: "t0",
            actual: 2,
            maximum: 1,
        }
    ));
    assert_eq!(break_reader.position(), 3);
    assert_eq!(&break_reader.get_ref()[3..], &[0xaa, 2]);

    assert_eq!(
        HasMore1::read_from(&mut Cursor::new([1, 7, 0]), &context).unwrap(),
        HasMore1(vec![7])
    );
    let mut has_more_reader = Cursor::new([1, 7, 1, 0xbb, 0]);
    let error = HasMore1::read_from(&mut has_more_reader, &context)
        .expect_err("second has-more element must exceed the policy");
    assert!(matches!(
        error,
        SerializationError::CollectionLengthLimitExceeded {
            field: "t0",
            actual: 2,
            maximum: 1,
        }
    ));
    assert_eq!(has_more_reader.position(), 3);
    assert_eq!(&has_more_reader.get_ref()[3..], &[0xbb, 0]);
}

#[test]
fn zero_limit_accepts_terminal_markers_and_invalid_markers_keep_precedence() {
    let context = context_with_collection_limit(0);

    assert_eq!(
        Break1::read_from(&mut Cursor::new([2]), &context).unwrap(),
        Break1(Vec::new())
    );
    assert_eq!(
        HasMore1::read_from(&mut Cursor::new([0]), &context).unwrap(),
        HasMore1(Vec::new())
    );

    let error = Break1::read_from(&mut Cursor::new([3]), &context)
        .expect_err("marker validation must happen before any limit check");
    assert!(matches!(
        error,
        SerializationError::InvalidSequenceMarker {
            field: "t0",
            value: 3,
        }
    ));

    let error = HasMore1::read_from(&mut Cursor::new([2]), &context)
        .expect_err("has-more marker validation must precede the limit check");
    assert!(matches!(
        error,
        SerializationError::InvalidSequenceMarker {
            field: "t0",
            value: 2,
        }
    ));
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct OptionWidths {
    #[silkroad(size = 1)]
    one: Option<u8>,
    #[silkroad(size = 2)]
    two: Option<u8>,
    #[silkroad(size = 4)]
    four: Option<u8>,
    #[silkroad(size = 8)]
    eight: Option<u8>,
}

#[test]
fn options_honor_all_presence_widths() {
    assert_round_trip(
        OptionWidths {
            one: None,
            two: Some(2),
            four: None,
            eight: Some(8),
        },
        &[
            0, // u8 None
            1, 0, 2, // u16 Some
            0, 0, 0, 0, // u32 None
            1, 0, 0, 0, 0, 0, 0, 0, 8, // u64 Some
        ],
        &SerdeContext::default(),
    );
    assert_round_trip(
        OptionWidths {
            one: Some(1),
            two: None,
            four: Some(4),
            eight: None,
        },
        &[
            1, 1, // u8 Some
            0, 0, // u16 None
            1, 0, 0, 0, 4, // u32 Some
            0, 0, 0, 0, 0, 0, 0, 0, // u64 None
        ],
        &SerdeContext::default(),
    );
}

#[test]
fn invalid_option_marker_is_rejected() {
    let error = OptionWidths::read_from(&mut Cursor::new([2]), &SerdeContext::default())
        .expect_err("invalid option marker must fail");
    assert!(matches!(
        error,
        SerializationError::InvalidPresenceMarker {
            field: "one",
            value: 2
        }
    ));
}

#[test]
fn conditional_option_state_must_match_its_condition() {
    for value in [
        TestCond {
            cond: 1,
            unrelated: String::new(),
            value: None,
        },
        TestCond {
            cond: 0,
            unrelated: String::new(),
            value: Some(1),
        },
    ] {
        assert_serialization_error(&value, &SerdeContext::default(), |error| {
            matches!(
                error,
                SerializationError::ConditionalPresenceMismatch { field: "value", .. }
            )
        });
    }
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct ExplicitMarkerlessConditional {
    enabled: bool,
    #[silkroad(size = 0, when = "enabled")]
    value: Option<u16>,
}

#[test]
fn size_zero_with_when_is_a_decodable_conditional_option() {
    assert_round_trip(
        ExplicitMarkerlessConditional {
            enabled: true,
            value: Some(0x1234),
        },
        &[1, 0x34, 0x12],
        &SerdeContext::default(),
    );
}

#[test]
fn derived_boolean_fields_reject_noncanonical_values() {
    let mut input = Cursor::new([2, 0x34, 0x12]);

    let error = ExplicitMarkerlessConditional::read_from(&mut input, &SerdeContext::default())
        .expect_err("a derived boolean field must reject values other than zero or one");

    assert!(matches!(
        error,
        SerializationError::InvalidBooleanValue { value: 2 }
    ));
    assert_eq!(input.position(), 1);
}

#[derive(Serialize, ByteSize)]
struct BareOption(#[silkroad(size = 0)] Option<u16>);

#[test]
fn bare_options_are_supported_for_serialize_and_size() {
    let none = BareOption(None);
    let some = BareOption(Some(0x1234));
    assert_eq!(none.byte_size(), 0);
    assert_eq!(some.byte_size(), 2);

    let mut output = BytesMut::new();
    none.write_to(&mut output, &SerdeContext::default())
        .unwrap();
    some.write_to(&mut output, &SerdeContext::default())
        .unwrap();
    assert_eq!(output.as_ref(), &[0x34, 0x12]);
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct CalculatedCollection {
    count: i16,
    #[silkroad(list_type = "calculated", calculate = "count")]
    values: Vec<u8>,
    trailing: u8,
}

#[test]
fn calculated_collections_have_no_local_prefix() {
    assert_round_trip(
        CalculatedCollection {
            count: 0,
            values: Vec::new(),
            trailing: 12,
        },
        &[0, 0, 12],
        &SerdeContext::default(),
    );
    assert_round_trip(
        CalculatedCollection {
            count: 2,
            values: vec![10, 11],
            trailing: 12,
        },
        &[2, 0, 10, 11, 12],
        &SerdeContext::default(),
    );
}

#[test]
fn calculated_collection_length_is_validated() {
    assert_serialization_error(
        &CalculatedCollection {
            count: 1,
            values: vec![1, 2],
            trailing: 0,
        },
        &SerdeContext::default(),
        |error| {
            matches!(
                error,
                SerializationError::CalculatedLengthMismatch {
                    field: "values",
                    expected: 1,
                    actual: 2
                }
            )
        },
    );
    assert_serialization_error(
        &CalculatedCollection {
            count: -1,
            values: Vec::new(),
            trailing: 0,
        },
        &SerdeContext::default(),
        |error| {
            matches!(
                error,
                SerializationError::CalculatedLengthOutOfRange { field: "values" }
            )
        },
    );
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct ContextCalculatedCollection(
    #[silkroad(
        list_type = "calculated",
        calculate = "ctx.get::<usize>().unwrap_or(0)"
    )]
    Vec<u8>,
);

#[test]
fn calculated_collection_expressions_can_use_context() {
    let ctx = SerdeContext::default();
    ctx.set(2usize);
    let value = ContextCalculatedCollection(vec![5, 6]);
    assert_eq!(value.byte_size(), 2);
    let mut output = BytesMut::new();
    value.write_to(&mut output, &ctx).unwrap();
    assert_eq!(output.as_ref(), &[5, 6]);
    assert_eq!(
        ContextCalculatedCollection::read_from(&mut Cursor::new([5, 6, 0xaa]), &ctx).unwrap(),
        value
    );
}

#[derive(Deserialize, Eq, PartialEq, Debug)]
struct WideCalculatedCollection {
    count: u64,
    #[silkroad(list_type = "calculated", calculate = "count")]
    values: Vec<u8>,
}

#[test]
fn calculated_collections_check_limits_before_reading_elements() {
    let context = context_with_collection_limit(2);
    assert_eq!(
        WideCalculatedCollection::read_from(
            &mut Cursor::new([2, 0, 0, 0, 0, 0, 0, 0, 7, 8]),
            &context,
        )
        .unwrap(),
        WideCalculatedCollection {
            count: 2,
            values: vec![7, 8],
        }
    );

    let mut reader = Cursor::new([3, 0, 0, 0, 0, 0, 0, 0, 0xaa]);
    let error = WideCalculatedCollection::read_from(&mut reader, &context)
        .expect_err("calculated count above the policy must fail");
    assert!(matches!(
        error,
        SerializationError::CollectionLengthLimitExceeded {
            field: "values",
            actual: 3,
            maximum: 2,
        }
    ));
    assert_eq!(reader.position(), 8);
    assert_eq!(&reader.get_ref()[8..], &[0xaa]);
}

#[derive(Clone)]
struct ExpressionCounter(std::sync::Arc<std::sync::atomic::AtomicUsize>);

#[derive(Deserialize)]
struct OnceCalculatedCollection(
    #[silkroad(
        list_type = "calculated",
        calculate = "{ ctx.get::<ExpressionCounter>().unwrap().0.fetch_add(1, \
                     std::sync::atomic::Ordering::SeqCst); 0usize }"
    )]
    Vec<u8>,
);

#[test]
fn calculated_collection_expression_is_evaluated_once() {
    let counter = std::sync::Arc::new(std::sync::atomic::AtomicUsize::new(0));
    let context = SerdeContext::default();
    context.set(ExpressionCounter(std::sync::Arc::clone(&counter)));

    let decoded = OnceCalculatedCollection::read_from(&mut Cursor::new([]), &context).unwrap();

    assert!(decoded.0.is_empty());
    assert_eq!(counter.load(std::sync::atomic::Ordering::SeqCst), 1);
}

#[test]
fn calculated_length_range_errors_are_preserved_during_deserialization() {
    let error = CalculatedCollection::read_from(
        &mut Cursor::new((-1i16).to_le_bytes()),
        &SerdeContext::default(),
    )
    .expect_err("negative calculated count cannot become usize");
    assert!(matches!(
        error,
        SerializationError::CalculatedLengthOutOfRange { field: "values" }
    ));
}

#[cfg(target_pointer_width = "64")]
#[test]
fn calculated_capacity_overflow_returns_a_typed_allocation_error() {
    let error = WideCalculatedCollection::read_from(
        &mut Cursor::new(u64::MAX.to_le_bytes()),
        &SerdeContext::default(),
    )
    .expect_err("usize::MAX elements cannot be reserved for Vec<u8>");
    assert!(matches!(
        error,
        SerializationError::CollectionAllocationFailed {
            field: "values",
            elements: u64::MAX,
            ..
        }
    ));
}

#[cfg(target_pointer_width = "32")]
#[test]
fn calculated_allocation_and_range_failures_remain_distinct() {
    let error = WideCalculatedCollection::read_from(
        &mut Cursor::new(u64::from(u32::MAX).to_le_bytes()),
        &SerdeContext::default(),
    )
    .expect_err("usize::MAX elements cannot be reserved for Vec<u8>");
    assert!(matches!(
        error,
        SerializationError::CollectionAllocationFailed {
            field: "values",
            elements: value,
            ..
        } if value == u64::from(u32::MAX)
    ));

    let error = WideCalculatedCollection::read_from(
        &mut Cursor::new(u64::MAX.to_le_bytes()),
        &SerdeContext::default(),
    )
    .expect_err("u64::MAX cannot become a 32-bit usize");
    assert!(matches!(
        error,
        SerializationError::CalculatedLengthOutOfRange { field: "values" }
    ));
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct SyntheticScalar {
    raw: u8,
    #[silkroad(calculate = "u16::from(raw) + ctx.get::<u16>().unwrap_or(0)")]
    calculated: u16,
}

#[test]
fn synthetic_scalars_are_omitted_and_canonicalized() {
    let ctx = SerdeContext::default();
    ctx.set(10u16);
    let canonical = SyntheticScalar {
        raw: 2,
        calculated: 12,
    };
    assert_eq!(canonical.byte_size(), 1);
    let mut output = BytesMut::new();
    canonical.write_to(&mut output, &ctx).unwrap();
    assert_eq!(output.as_ref(), &[2]);
    let decoded = SyntheticScalar::read_from(&mut Cursor::new([2]), &ctx).unwrap();
    assert_eq!(decoded, canonical);

    let noncanonical = SyntheticScalar {
        raw: 2,
        calculated: 99,
    };
    let mut output = BytesMut::new();
    noncanonical.write_to(&mut output, &ctx).unwrap();
    let decoded = SyntheticScalar::read_from(&mut Cursor::new(output), &ctx).unwrap();
    assert_eq!(decoded.calculated, 12);
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct ArrayAndTuple {
    empty: [u8; 0],
    words: [u16; 2],
    custom: [Test; 1],
    unit: (),
    single: (u8,),
}

struct FailingElement;

impl ByteSize for FailingElement {
    fn byte_size(&self) -> usize {
        0
    }
}

impl Serialize for FailingElement {
    fn write_to(
        &self,
        _writer: &mut BytesMut,
        _ctx: &SerdeContext,
    ) -> Result<(), SerializationError> {
        Err(SerializationError::CalculatedLengthOutOfRange { field: "element" })
    }
}

#[test]
fn generic_array_serialization_propagates_element_errors() {
    let mut output = BytesMut::new();
    let error = [FailingElement]
        .write_to(&mut output, &SerdeContext::default())
        .expect_err("element failure must propagate");
    assert!(matches!(
        error,
        SerializationError::CalculatedLengthOutOfRange { field: "element" }
    ));
}

#[test]
fn generic_arrays_and_tuple_edge_cases_round_trip() {
    assert_round_trip(
        ArrayAndTuple {
            empty: [],
            words: [0x1234, 0x5678],
            custom: [Test {
                one: 1,
                two: 2,
                three: 3,
                four: 4,
            }],
            unit: (),
            single: (9,),
        },
        &[
            0x34, 0x12, 0x78, 0x56, 1, 2, 0, 3, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 9,
        ],
        &SerdeContext::default(),
    );
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct ClosureCondition {
    value: u8,
    values: [u8; 1],
    #[silkroad(when = "value == 4 && values.iter().any(|value| *value == 1)")]
    optional: Option<u8>,
}

#[test]
fn expression_rewriting_preserves_closure_bindings() {
    assert_round_trip(
        ClosureCondition {
            value: 4,
            values: [1],
            optional: Some(7),
        },
        &[4, 1, 7],
        &SerdeContext::default(),
    );
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct MatchesCondition {
    previous_field: u8,
    #[silkroad(when = "matches!(previous_field, 0x08)")]
    optional: Option<u16>,
}

#[test]
fn expression_rewriting_handles_matches_macro() {
    assert_round_trip(
        MatchesCondition {
            previous_field: 0x08,
            optional: Some(0x1234),
        },
        &[0x08, 0x34, 0x12],
        &SerdeContext::default(),
    );
    assert_round_trip(
        MatchesCondition {
            previous_field: 0x07,
            optional: None,
        },
        &[0x07],
        &SerdeContext::default(),
    );
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct ReservedFieldNames {
    reader: u8,
    ctx: u8,
    writer: u8,
    #[silkroad(when = "reader == 1 && ctx == 2 && writer == 3")]
    optional: Option<u16>,
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
enum EnumTagNameCollision {
    #[silkroad(when = "tag == 7")]
    Value {
        #[silkroad(tag)]
        selector: u8,
        tag: u16,
        writer: u8,
        ctx: u8,
    },
}

#[test]
fn generated_bindings_do_not_collide_with_fields_or_parameters() {
    assert_round_trip(
        ReservedFieldNames {
            reader: 1,
            ctx: 2,
            writer: 3,
            optional: Some(0x1234),
        },
        &[1, 2, 3, 0x34, 0x12],
        &SerdeContext::default(),
    );
    assert_round_trip(
        EnumTagNameCollision::Value {
            selector: 7,
            tag: 0x1234,
            writer: 8,
            ctx: 9,
        },
        &[7, 0x34, 0x12, 8, 9],
        &SerdeContext::default(),
    );
}

#[test]
fn predicate_serialization_enforces_first_match_order() {
    let value = TaggedEnum::B { value: 50 };
    assert_serialization_error(&value, &SerdeContext::default(), |error| {
        matches!(
            error,
            SerializationError::VariantConditionMismatch {
                enum_name: "TaggedEnum",
                variant: "B"
            }
        )
    });
}

#[derive(Clone, Copy)]
struct Selection(u8);

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct BindingScopeConditions {
    selection: u8,
    #[silkroad(
        when = "if let Some(selection) = ctx.get::<Selection>() { selection.0 == 1 } else { \
                selection == 7 }"
    )]
    if_let_value: Option<u8>,
    #[silkroad(
        when = "if let Some(later) = ctx.get::<Selection>() && later.0 == 1 { true } else { false \
                }"
    )]
    let_chain_value: Option<u8>,
    #[silkroad(when = "{ let mut enabled = false; while let Some(later) = \
                       ctx.get::<Selection>() { enabled = later.0 == 1; break; } enabled }")]
    while_let_value: Option<u8>,
    later: u8,
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
#[silkroad(size = 0)]
enum ScopedPredicateEnum {
    #[silkroad(
        when = "if let Some(value) = ctx.get::<Selection>() { value.0 == 1 } else { false }"
    )]
    Selected { value: u8 },
}

#[test]
fn expression_rewriting_honors_if_and_while_let_bindings() {
    let selected = SerdeContext::default();
    selected.set(Selection(1));
    assert_context_round_trip(
        BindingScopeConditions {
            selection: 0,
            if_let_value: Some(2),
            let_chain_value: Some(3),
            while_let_value: Some(4),
            later: 5,
        },
        &[0, 2, 3, 4, 5],
        &selected,
    );

    assert_round_trip(
        BindingScopeConditions {
            selection: 7,
            if_let_value: Some(2),
            let_chain_value: None,
            while_let_value: None,
            later: 5,
        },
        &[7, 2, 5],
        &SerdeContext::default(),
    );
}

#[test]
fn enum_predicates_ignore_locally_bound_body_field_names() {
    let context = SerdeContext::default();
    context.set(Selection(1));
    assert_context_round_trip(ScopedPredicateEnum::Selected { value: 9 }, &[9], &context);
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
#[silkroad(size = 0)]
enum ContextEnum {
    #[silkroad(when = "ctx.get::<Selection>().is_some_and(|selection| selection.0 == 1)")]
    One(u8),
    #[silkroad(when = "ctx.get::<Selection>().is_some_and(|selection| selection.0 == 2)")]
    Two(u8),
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
#[silkroad(size = 4)]
enum U32Enum {
    #[silkroad(value = 0x0102_0304)]
    Value,
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
#[silkroad(size = 8)]
enum U64Enum {
    #[silkroad(value = 0x0102_0304_0506_0708)]
    Value,
}

#[test]
fn fixed_enums_honor_four_and_eight_byte_discriminants() {
    assert_round_trip(U32Enum::Value, &[4, 3, 2, 1], &SerdeContext::default());
    assert_round_trip(
        U64Enum::Value,
        &[8, 7, 6, 5, 4, 3, 2, 1],
        &SerdeContext::default(),
    );

    let error = U64Enum::read_from(
        &mut Cursor::new(u64::MAX.to_le_bytes()),
        &SerdeContext::default(),
    )
    .expect_err("unknown u64 discriminant must fail losslessly");
    assert!(matches!(
        error,
        SerializationError::UnknownVariation(u64::MAX, "U64Enum")
    ));
}

#[test]
fn zero_width_enums_use_context_and_report_no_match() {
    let ctx = SerdeContext::default();
    ctx.set(Selection(2));
    let value = ContextEnum::Two(9);
    assert_eq!(value.byte_size(), 1);
    let mut output = BytesMut::new();
    value.write_to(&mut output, &ctx).unwrap();
    assert_eq!(output.as_ref(), &[9]);
    assert_eq!(
        ContextEnum::read_from(&mut Cursor::new([9]), &ctx).unwrap(),
        ContextEnum::Two(9)
    );

    ctx.set(Selection(1));
    let error = ContextEnum::Two(9)
        .write_to(&mut BytesMut::new(), &ctx)
        .expect_err("selected Rust variant must be the first matching predicate");
    assert!(matches!(
        error,
        SerializationError::VariantConditionMismatch {
            enum_name: "ContextEnum",
            variant: "Two"
        }
    ));

    ctx.unset::<Selection>();
    let error =
        ContextEnum::read_from(&mut Cursor::new([]), &ctx).expect_err("no selector should match");
    assert!(matches!(
        error,
        SerializationError::NoMatchingVariant {
            enum_name: "ContextEnum"
        }
    ));
}

#[derive(Clone)]
struct HookLog(std::sync::Arc<std::sync::Mutex<Vec<&'static str>>>);

#[derive(Clone)]
struct FailingHook(&'static str);

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
#[silkroad(
    before_serialize = "Self::before_serialize",
    after_serialize = "finish_hooked_packet",
    before_deserialize = "Self::before_deserialize",
    after_deserialize = "Self::after_deserialize"
)]
struct HookedPacket(u8);

impl HookedPacket {
    fn record(ctx: &SerdeContext, event: &'static str) -> Result<(), SerializationError> {
        ctx.get::<HookLog>()
            .expect("hook log missing from context")
            .0
            .lock()
            .expect("hook log lock poisoned")
            .push(event);
        if ctx
            .get::<FailingHook>()
            .is_some_and(|failure| failure.0 == event)
        {
            return Err(SerializationError::CalculatedLengthOutOfRange { field: event });
        }
        Ok(())
    }

    fn before_serialize(_packet: &Self, ctx: &SerdeContext) -> Result<(), SerializationError> {
        Self::record(ctx, "before_serialize")
    }

    fn before_deserialize(ctx: &SerdeContext) -> Result<(), SerializationError> {
        Self::record(ctx, "before_deserialize")
    }

    fn after_deserialize(_packet: &Self, ctx: &SerdeContext) -> Result<(), SerializationError> {
        Self::record(ctx, "after_deserialize")
    }
}

fn finish_hooked_packet(
    _packet: &HookedPacket,
    ctx: &SerdeContext,
) -> Result<(), SerializationError> {
    HookedPacket::record(ctx, "after_serialize")
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct HookedEnvelope(HookedPacket);

#[test]
fn container_hooks_run_around_successful_wire_operations() {
    let events = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));
    let ctx = SerdeContext::default();
    ctx.set(HookLog(events.clone()));
    let packet = HookedPacket(7);

    assert_eq!(packet.byte_size(), 1);
    assert!(events.lock().unwrap().is_empty(), "ByteSize ran hooks");

    let mut output = BytesMut::new();
    packet.write_to(&mut output, &ctx).unwrap();
    assert_eq!(output.as_ref(), &[7]);
    assert_eq!(
        events.lock().unwrap().as_slice(),
        &["before_serialize", "after_serialize"]
    );

    events.lock().unwrap().clear();
    let decoded = HookedPacket::read_from(&mut Cursor::new([9]), &ctx).unwrap();
    assert_eq!(decoded, HookedPacket(9));
    assert_eq!(
        events.lock().unwrap().as_slice(),
        &["before_deserialize", "after_deserialize"]
    );

    events.lock().unwrap().clear();
    let envelope = HookedEnvelope(HookedPacket(11));
    assert_eq!(envelope.byte_size(), 1);
    assert!(
        events.lock().unwrap().is_empty(),
        "nested ByteSize ran hooks"
    );
    envelope.write_to(&mut BytesMut::new(), &ctx).unwrap();
    assert_eq!(
        events.lock().unwrap().as_slice(),
        &["before_serialize", "after_serialize"]
    );

    events.lock().unwrap().clear();
    let decoded = HookedEnvelope::read_from(&mut Cursor::new([12]), &ctx).unwrap();
    assert_eq!(decoded, HookedEnvelope(HookedPacket(12)));
    assert_eq!(
        events.lock().unwrap().as_slice(),
        &["before_deserialize", "after_deserialize"]
    );
}

#[test]
fn hook_errors_are_propagated_at_each_lifecycle_point() {
    let events = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));
    let ctx = SerdeContext::default();
    ctx.set(HookLog(events));

    ctx.set(FailingHook("before_serialize"));
    let mut output = BytesMut::new();
    let error = HookedPacket(1).write_to(&mut output, &ctx).unwrap_err();
    assert!(matches!(
        error,
        SerializationError::CalculatedLengthOutOfRange {
            field: "before_serialize"
        }
    ));
    assert!(output.is_empty());

    ctx.set(FailingHook("after_serialize"));
    let mut output = BytesMut::new();
    let error = HookedPacket(2).write_to(&mut output, &ctx).unwrap_err();
    assert!(matches!(
        error,
        SerializationError::CalculatedLengthOutOfRange {
            field: "after_serialize"
        }
    ));
    assert_eq!(output.as_ref(), &[2]);

    ctx.set(FailingHook("before_deserialize"));
    let mut input = Cursor::new([3]);
    let error = HookedPacket::read_from(&mut input, &ctx).unwrap_err();
    assert!(matches!(
        error,
        SerializationError::CalculatedLengthOutOfRange {
            field: "before_deserialize"
        }
    ));
    assert_eq!(input.position(), 0);

    ctx.set(FailingHook("after_deserialize"));
    let mut input = Cursor::new([4]);
    let error = HookedPacket::read_from(&mut input, &ctx).unwrap_err();
    assert!(matches!(
        error,
        SerializationError::CalculatedLengthOutOfRange {
            field: "after_deserialize"
        }
    ));
    assert_eq!(input.position(), 1);
}

#[derive(Serialize, ByteSize)]
#[silkroad(
    before_serialize = "Self::before_serialize",
    after_serialize = "Self::after_serialize"
)]
struct HookedSerializationFailure(FailingElement);

impl HookedSerializationFailure {
    fn before_serialize(_packet: &Self, ctx: &SerdeContext) -> Result<(), SerializationError> {
        HookedPacket::record(ctx, "before_serialize")
    }

    fn after_serialize(_packet: &Self, ctx: &SerdeContext) -> Result<(), SerializationError> {
        HookedPacket::record(ctx, "after_serialize")
    }
}

#[allow(dead_code)]
#[derive(Deserialize, Debug)]
#[silkroad(
    before_deserialize = "Self::before_deserialize",
    after_deserialize = "Self::after_deserialize"
)]
struct HookedDeserializationFailure(u16);

impl HookedDeserializationFailure {
    fn before_deserialize(ctx: &SerdeContext) -> Result<(), SerializationError> {
        HookedPacket::record(ctx, "before_deserialize")
    }

    fn after_deserialize(_packet: &Self, ctx: &SerdeContext) -> Result<(), SerializationError> {
        HookedPacket::record(ctx, "after_deserialize")
    }
}

#[test]
fn after_hooks_do_not_run_when_wire_operations_fail() {
    let events = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));
    let ctx = SerdeContext::default();
    ctx.set(HookLog(events.clone()));

    HookedSerializationFailure(FailingElement)
        .write_to(&mut BytesMut::new(), &ctx)
        .expect_err("field serialization should fail");
    assert_eq!(events.lock().unwrap().as_slice(), &["before_serialize"]);

    events.lock().unwrap().clear();
    HookedDeserializationFailure::read_from(&mut Cursor::new([1]), &ctx)
        .expect_err("truncated u16 should fail");
    assert_eq!(events.lock().unwrap().as_slice(), &["before_deserialize"]);
}
