#![cfg(test)]

use bytes::BytesMut;
use skrillax_serde::{ByteSize, Deserialize, SerdeContext, SerializationError, Serialize};
use std::fmt::Debug;
use std::io::Cursor;

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct Test {
    one: u8,
    two: u16,
    three: u32,
    four: u64,
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
enum TestEnum {
    #[silkroad(value = 1)]
    A,
    #[silkroad(value = 2)]
    B(u8),
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct Wrapped {
    inner: Test,
    inner2: TestEnum,
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct NormalString(String);

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct DoubleString(#[silkroad(size = 2)] String);

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct WithVec(Vec<u32>);

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
enum EnumWithNamedVec {
    #[silkroad(value = 1)]
    Variant { inner: Vec<Test> },
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
struct TestCond {
    cond: u8,
    unrelated: String,
    #[silkroad(when = "cond == 1")]
    value: Option<u8>,
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
#[silkroad(size = 2)]
enum LargerEnum {
    #[silkroad(value = 1)]
    A,
    #[silkroad(value = 0xFFF)]
    B,
}

/// Assert the complete contract for a successfully serialized value.
///
/// The prefix proves that serialization writes at the current buffer position,
/// while the trailing canary proves that deserialization stops exactly at the
/// end of the value.
fn assert_round_trip<T>(value: T, expected: &[u8], ctx: &SerdeContext)
where
    T: Serialize + Deserialize + Eq + Debug,
    bytes::Bytes: TryFrom<T, Error = SerializationError>,
{
    assert_eq!(expected.len(), value.byte_size());

    const PREFIX: &[u8] = &[0xA5, 0x5A];
    let mut output = BytesMut::from(PREFIX);
    let initial_len = output.len();

    let result = value.write_to(&mut output, ctx);
    assert!(result.is_ok(), "serialization failed: {:?}", result);
    assert_eq!(PREFIX, &output[..initial_len]);

    let written = &output[initial_len..];
    assert_eq!(value.byte_size(), written.len());
    assert_eq!(expected, written);

    let decoded = assert_deserializes_exactly::<T>(expected, ctx);
    assert_eq!(value, decoded);

    let converted = bytes::Bytes::try_from(value).expect("generated byte conversion failed");
    assert_eq!(expected, converted.as_ref());
}

/// Deserialize a value with a trailing canary and verify that the reader
/// consumed exactly the value, not any following bytes.
fn assert_deserializes_exactly<T>(expected: &[u8], ctx: &SerdeContext) -> T
where
    T: Deserialize,
{
    const CANARY: &[u8] = &[0xCA, 0xFE, 0xBA, 0xBE];
    let mut input = Vec::with_capacity(expected.len() + CANARY.len());
    input.extend_from_slice(expected);
    input.extend_from_slice(CANARY);
    let mut reader = Cursor::new(input);
    let decoded = T::read_from(&mut reader, ctx).expect("deserialization failed");

    assert_eq!(expected.len() as u64, reader.position());
    assert_eq!(CANARY, &reader.get_ref()[reader.position() as usize..]);
    decoded
}

/// Assert that serialization returns the expected typed error.
#[allow(dead_code)]
fn assert_serialization_error<T, F>(value: &T, ctx: &SerdeContext, matches: F)
where
    T: Serialize,
    F: FnOnce(&SerializationError) -> bool,
{
    let mut output = BytesMut::new();
    let error = value
        .write_to(&mut output, ctx)
        .expect_err("serialization unexpectedly succeeded");
    assert!(matches(&error), "unexpected serialization error: {error:?}");
}

macro_rules! test_serialize_deserialize {
    ($ty:ty, $init:expr, $expected:expr) => {{
        assert_round_trip::<$ty>($init, $expected, &SerdeContext::default());
    }};
}

#[test]
pub fn test_simple() {
    test_serialize_deserialize!(
        Test,
        Test {
            one: 1,
            two: 2,
            three: 3,
            four: 4,
        },
        &[1, 2, 0, 3, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0]
    );
}

#[test]
pub fn test_enum() {
    test_serialize_deserialize!(TestEnum, TestEnum::A, &[1]);
    test_serialize_deserialize!(TestEnum, TestEnum::B(1), &[2, 1]);
}

#[test]
pub fn test_wrapped() {
    test_serialize_deserialize!(
        Wrapped,
        Wrapped {
            inner: Test {
                one: 1,
                two: 2,
                three: 3,
                four: 4,
            },
            inner2: TestEnum::B(3),
        },
        &[1, 2, 0, 3, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 2, 3,]
    );
}

#[test]
pub fn test_strings() {
    test_serialize_deserialize!(
        NormalString,
        NormalString("123".to_string()),
        &[3, 0, b'1', b'2', b'3']
    );
    test_serialize_deserialize!(
        DoubleString,
        DoubleString("456".to_string()),
        &[3, 0, b'4', 0, b'5', 0, b'6', 0]
    );
}

#[test]
pub fn test_vec() {
    test_serialize_deserialize!(
        WithVec,
        WithVec(vec![123, 456, 789]),
        &[3, 123, 0, 0, 0, 200, 1, 0, 0, 21, 3, 0, 0]
    );
    test_serialize_deserialize!(
        EnumWithNamedVec,
        EnumWithNamedVec::Variant {
            inner: vec![Test {
                one: 0,
                two: 0,
                three: 0,
                four: 0,
            }],
        },
        &[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]
    );
}

#[test]
pub fn test_cond() {
    test_serialize_deserialize!(
        TestCond,
        TestCond {
            cond: 1,
            unrelated: String::from("abc"),
            value: Some(1),
        },
        &[1, 3, 0, b'a', b'b', b'c', 1]
    );

    test_serialize_deserialize!(
        TestCond,
        TestCond {
            cond: 0,
            unrelated: String::from("abc"),
            value: None,
        },
        &[0, 3, 0, b'a', b'b', b'c']
    );
}

#[test]
pub fn test_large_enum() {
    test_serialize_deserialize!(LargerEnum, LargerEnum::B, &[0xFF, 0x0F]);
}

#[test]
pub fn test_unknown_variant() {
    let bytes = bytes::Bytes::from_static(&[3u8]);
    assert!(matches!(
        TestEnum::try_from(bytes),
        Err(skrillax_serde::SerializationError::UnknownVariation(
            3, "TestEnum"
        ))
    ));
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
#[silkroad(size = 2)]
enum TaggedEnum {
    #[silkroad(when = "tag < 100")]
    A {
        #[silkroad(tag)]
        value: u16,
    },
    #[silkroad(when = "(100..=300).contains(&tag)")]
    B {
        #[silkroad(tag)]
        value: u16,
    },
    #[silkroad(when = "tag >= 301")]
    C {
        #[silkroad(tag)]
        value: u16,
    },
}

#[test]
pub fn test_tagged_enum() {
    test_serialize_deserialize!(TaggedEnum, TaggedEnum::A { value: 50 }, &[50, 0]);
    test_serialize_deserialize!(TaggedEnum, TaggedEnum::B { value: 150 }, &[150, 0]);
    test_serialize_deserialize!(TaggedEnum, TaggedEnum::C { value: 1240 }, &[0xD8, 0x04]);
}

#[derive(Serialize, ByteSize, Deserialize, Eq, PartialEq, Debug)]
#[silkroad(size = 2)]
enum TaggedTupleEnum {
    #[silkroad(when = "tag < 100")]
    A(#[silkroad(tag)] u16),
    #[silkroad(when = "(100..=300).contains(&tag)")]
    B(#[silkroad(tag)] u16),
    #[silkroad(when = "tag >= 301")]
    C(#[silkroad(tag)] u16),
}

#[test]
pub fn test_tagged_tuple_enum() {
    test_serialize_deserialize!(TaggedTupleEnum, TaggedTupleEnum::A(50), &[50, 0]);
    test_serialize_deserialize!(TaggedTupleEnum, TaggedTupleEnum::B(150), &[150, 0]);
    test_serialize_deserialize!(TaggedTupleEnum, TaggedTupleEnum::C(1240), &[0xD8, 0x04]);
}
