[package]
name = "skrillax-serde-derive"
version = "0.3.0"
authors = ["kumpelblase2"]
description = "Derive macro to automatically implement seralization/deserialization for stuctures."
license = "MIT"
repository = "https://git.eternalwings.de/tim/skrillax-network"
keywords = ["silkroad", "serde"]
edition.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]
darling = "0.23"
proc-macro2-diagnostics = "0.10"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "visit", "visit-mut"] }

[lib]
proc-macro = true
test = false
doctest = false
