on:
  push:
    branches: [ master ]
  pull_request:

name: test
jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: test ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: cache cargo
        uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@nextest
      - name: test
        run: just test